server:
  port : 8761
  enableSelfPreservation: false
eureka:
  client:
      register-with-eureka: false
      fetch-registry: false
spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false      
   